#!/bin/bash

echo
echo m8ke-script 0.1
echo ===============

if [ -z $1 ]
then
	for THEME in 'src/themes'/*
	do
		THEME_BASE=$(basename $THEME)
		echo $THEME_BASE/build.less found
		echo Compiling $THEME_BASE.min.css, please wait
		lessc -x src/themes/$THEME_BASE/build.less dist/$THEME_BASE.min.css
	done
else
	THEME=$1
	echo $THEME/build.less found
	echo Compiling $THEME.min.css, please wait
	lessc -x src/themes/$THEME/build.less dist/$THEME.min.css
fi

echo
echo Completed.