#!/bin/bash
VERSION=0.3
echo $'\n'm8ke-script $VERSION
echo ===============

function die(){
 echo $1
 exit 1
}

if [ -e 'bower_components' ]
then
    echo Bower components seem to be in place
else
	echo Bower components not found
	echo Downloading components
	bower install || die 'You need to install Bower before you can continue (http://bower.io/)'
fi

if [ -z $1 ]
then
	for THEME in 'src/themes'/*
	do
		THEME_BASE=$(basename $THEME)
		echo $'\n'$THEME_BASE/build.less found
		echo Compiling $THEME_BASE.min.css, please wait
		lessc -x src/themes/$THEME_BASE/build.less dist/$THEME_BASE.min.css
	done
else
	THEME=$1
    echo $'\n'$THEME/build.less found
	echo Compiling $THEME.min.css, please wait
	lessc -x src/themes/$THEME/build.less dist/$THEME.min.css
fi

echo $'\n'Completed.