#!/bin/bash

VERSION=0.4
set -e

# Functions
function npm_error(){
    echo "You need to install Node before we can continue (http://nodejs.org/)"
    exit 1
}

function bower_error(){
    while true; do
        read -p "Bower is not installed. Do you want to install it now? (y/n) " yn
        case $yn in
            [Yy*]* ) npm install bower || npm_error; break;;
            [Nn]* ) echo 'Aborted by user.'; exit;;
        esac
    done

    echo 'done that'
    exit
}

# Let's go
echo $'\n'm8ke-script $VERSION
echo ===============

if [ -e 'bower_components' ]
then
    echo Bower components seem to be in place
else
	echo Bower components not found
	echo Downloading components
	bower install || bower_error
fi

if [ -z $1 ]
then
	for THEME in 'src/themes'/*
	do
		THEME_BASE=$(basename $THEME)
		echo $'\n'$THEME_BASE/build.less found
		echo Compiling $THEME_BASE.min.css, please wait $'\n'
		lessc -x src/themes/$THEME_BASE/build.less dist/css/m8tro.min.css
	done
else
	THEME=$1
    echo $'\n'$THEME/build.less found
	echo Compiling $THEME.min.css, please wait $'\n'
	lessc -x src/themes/$THEME/build.less dist/css/$THEME.min.css
fi

if [ ! -e 'dist/js/' ]
then
    echo 'Make directory ./dist/js/'
    mkdir ./dist/js/
fi

echo "Copying JavaScript"
cp -f ./bower_components/bootstrap/dist/js/bootstrap.min.js ./dist/js/
cp -f ./bower_components/jquery/dist/jquery.min.js ./dist/js/

if [ ! -e 'dist/fonts/' ]
then
    echo 'Make directory ./dist/fonts/'
    mkdir ./dist/fonts/
fi

echo "Copying Font Awesome"
cp -f ./bower_components/fontawesome/css/font-awesome.min.css ./dist/css/
cp -f ./bower_components/fontawesome/fonts/*.* ./dist/fonts/

echo $'\n'Completed.